### ISSUE TITLE
Integração da Máquina de Regras com a Movimentação

### ISSUE THREAD

**Issue by jpsmedeiros** [Vipkry/damas-es2#19]
- [x] Colocar estadoAtual no GameController
- [x] Chamar a MaquinaDeRegras antes de fazer uma movimentação para adquirir os movimentos possiveis
- [x] Otimizar chamada da MaquinaDeRegras para ser chamada apenas uma vez, após passar o turno

- Uma chamada ao inicializar a classe Movimentação.

- Outra chamada ao realizar uma movimentação.

- [x] Verificar se movimento que estou querendo fazer se encontra na lista de jogadas
- [x] Impedir movimentação caso não esteja na lista de jogadas possíveis para tal peça mostrando indicativo visual de jogada inválida
- [x] Mostrar highlight no tabuleiro quando peça é selecionada
- [x] Executar movimento visual seguindo as ações da Jogada, quando uma movimentação é aceita
- [x] Executar movimento visual de movimentos multiplos

**Comment by Vipkry** [comment]
criar highlight aqui
