### ISSUE TITLE
Animação de captura não está considerando casas intermediárias

### ISSUE THREAD

**Issue by gabrielcs23** [Vipkry/damas-es2#38]
Branch: #19_integracao_regras
Ao fazer mais de uma captura em uma única jogada, a peça se movimenta diretamente para a casa final do movimento (último valor na lista Jogada.movimentos) ao invés de passar nas casas intermediárias. 
![bug_animacao](https://user-images.githubusercontent.com/13492277/41293458-ad4fcbae-6e2b-11e8-8ea8-12b7227379fa.gif)

**Comment by jpsmedeiros** [comment]
Pronto
![fix](https://i.imgur.com/E7sDOnJ.gif)
