### ISSUE TITLE
Tratar Regras de Empate listadas

### ISSUE THREAD

**Issue by jpsmedeiros** [Vipkry/damas-es2#42]
- [x] 2 damas contra 2 damas;

- [x] 2 damas contra uma;

- [x] 2 damas contra uma dama e uma pedra;

- [x] uma dama contra uma dama e uma dama contra uma dama e uma pedra, são declarados empatados após 5 lances de cada jogador.

**Comment by Vipkry** [comment]
@jpsmedeiros eu acho que isso fechou algumas partes certo?
